version: '3.5'

services:
  db:
    container_name: book_rental_db
    image: mysql/mysql-server:8.0.21
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: student_management
      MYSQL_USER: admin
      MYSQL_PASSWORD: secret
      TZ: Asia/Istanbul
  redis:
    container_name: redis_cache
    image: redis:alpine3.14
    hostname: redis
    ports:
      - 6379:6379