server:
  port: 8082

spring:
  redis:
    host: redis
    port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/student_management
    username: admin
    password: secret
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      ddl-auto: create
    generate-ddl: true
    properties:
      hibernate:
        format-sql: true


keycloak-client-id: student-management-rest-api-local
keycloak-client-secret: 6789014c-4dab-436c-b53d-6d746484e0d8
keycloak-realm: student-management
keycloak-auth-admin-url: http://localhost:8084/auth/admin/realms/student-management
keycloak-token-url: http://localhost:8084/auth/realms/student-management/protocol/openid-connect/token

seeder-base-url: http://localhost:5000/api/v1

keycloak:
  config:
    file-path: "/keycloak/keycloak-local.json"


redis:
  host: localhost
  port: 6379

kafka:
  topics: user_register
  group-id: keycloak
  bootstrap-servers: localhost:9092

swagger:
  server:
    url: http://localhost:8082